Repository minishell-jiphyeonjeon/Rank03-Minishell, pull requests merged in 2022-03, with the labels that each got.

#118 소소한 이슈 해결
  src/api/env2.c
  src/scanner/scanner.c
Labels: Bug 🐛, Feature ⭐

#120 파이프 에러 해결
  include/api.h
  include/ast_type.h
  include/builtin.h
  include/exec.h
  include/minishell.h
  include/minishell_type.h
  include/pipe.h
  include/shell.h
  lib/Makefile
  lib/include/error.h
  makefile
  src/api/util.c
  src/builtin/cd.c
  src/builtin/checks.c
  src/exec/context.c
  src/exec/exec.c
  src/exec/pipe.c
  src/exec/util.c
  src/pipe/pipe.c
  src/pipe/send.c
  src/pipe/status.c
  src/pipe/util.c
  src/shell/shell.c
Labels: Bug 🐛, Feature ⭐, Refactor ⚙️

#121 몬가 많은 버그픽스들
  include/api.h
  include/ast_type.h
  include/builtin.h
  include/errormsg.h
  include/minishell.h
  include/minishell_type.h
  include/open.h
  include/scanner.h
  lib/Makefile
  lib/include/ft_math.h
  lib/include/ft_string.h
  lib/src/ft_math/check.c
  lib/src/ft_math/compare.c
  lib/src/ft_math/math.c
  lib/src/ft_string/check.c
  makefile
  src/api/path.c
  src/api/redirect.c
  src/api/tilde.c
  src/builtin/builtin.c
  src/builtin/cd.c
  src/builtin/exit.c
  src/errormsg/error.c
  src/exec/context.c
  src/exec/exec.c
  src/main.c
  src/open/file.c
  src/open/heredoc.c
  src/open/open.c
  src/open/redirect.c
  src/open/util.c
  src/parser/new2.c
  src/prompt/util.c
  src/scanner/util2.c
  src/shell/script.c
  src/shell/shell.c
Labels: Bug 🐛

#123 더 많은 버그픽스!!!!
  include/ast_type.h
  include/exec.h
  include/pipe.h
  include/scanner.h
  include/shell.h
  src/api/env2.c
  src/api/path.c
  src/builtin/cd.c
  src/builtin/checks.c
  src/builtin/pwd.c
  src/exec/util.c
  src/open/open.c
  src/open/redirect.c
  src/pipe/pipe.c
  src/pipe/send.c
  src/pipe/status.c
  src/pipe/util.c
  src/scanner/metachar_scan1.c
  src/scanner/scanner.c
  src/scanner/util2.c
  src/scanner/util3.c
  src/shell/script.c
Labels: Bug 🐛

#128 heredoc 오류 해결
  include/builtin.h
  include/exec.h
  include/open.h
  include/prompt.h
  lib/include/system.h
  lib/src/system/alloc.c
  makefile
  src/builtin/check.c
  src/exec/context.c
  src/exec/util.c
  src/open/heredoc.c
  src/open/open.c
  src/open/redirect.c
  src/prompt/check.c
  src/prompt/util.c
Labels: Bug 🐛

#131 fix: :bug: Fix exit bugs
  lib/include/error.h
  lib/src/ft_math/math.c
  src/builtin/exit.c
Labels: Bug 🐛
