Repository minishell-jiphyeonjeon/Rank03-Minishell, pull requests merged in 2022-02, with the labels that each got.

#17 ci: :construction_worker: Create CODEOWNERS
  .github/CODEOWNERS
Labels: CI/Project 👷

#16 feat: :sparkles: Add string library functions
  .gitignore
  include/minishell.h
  lib/Makefile
  lib/include/color.h
  lib/include/libft.h
  lib/include/string.h
  lib/include/system.h
  lib/include/type.h
  lib/includes/string.h
  lib/includes/system.h
  lib/src/string/array.c
  lib/src/string/join.c
  lib/src/string/new.c
  lib/src/string/split.c
  lib/src/string/util.c
  makefile
  makefile-prev.mk
  src/main.c
Labels: Feature ⭐

#31 fix: :bug: Fix header include error
  include/minishell.h
  lib/include/color.h
  makefile
Labels: Bug 🐛

#38 feat: :sparkles: Improve `tokens_print()` print format
  src/lexer/lexer_tokenizer.c
Labels: Feature ⭐

#40 feat: :sparkles: Create AST Structure
  include/ast_node.h
  include/ast_type.h
  include/lexer.h
  include/minishell.h
  include/minishell_type.h
  src/lexer/lexer_tokenizer.c
  structure.yaml
Labels: Feature ⭐, Docs 📑

#37 feat: ✨ Renew interactive prompt
  include/minishell.h
  include/prompt.h
  lib/include/string.h
  makefile
  src/main.c
  src/prompt/interrupt.c
  src/prompt/prompt.c
  src/prompt/util.c
Labels: Bug 🐛, Feature ⭐, Refactor ⚙️

#39 feat: :sparkles: Implement Env
  include/builtin.h
  include/minishell.h
  lib/Makefile
  lib/include/dict.h
  lib/include/libft.h
  lib/include/string.h
  lib/include/type.h
  lib/src/dict/del.c
  lib/src/dict/expand.c
  lib/src/dict/get.c
  lib/src/dict/hash.c
  lib/src/dict/new.c
  lib/src/dict/print.c
  lib/src/dict/set.c
  lib/src/dict/status.c
  lib/src/string/array.c
  lib/src/string/join.c
  makefile
  src/builtin/env.c
  src/builtin/path.c
  src/main.c
Labels: Feature ⭐

#42 feat: :sparkles: Improve lexer_tokenizer
  include/lexer.h
  src/lexer/lexer.c
  src/lexer/lexer_tokenizer.c
Labels: Feature ⭐

#49 feat: :sparkles: Add `new_str_join_freed()`
  lib/include/string.h
  lib/src/string/join.c
Labels: Feature ⭐

#47 fix: 🐛 Make arrays in ast node able to be NULL terminated
  include/ast_node.h
  lib/include/ft_math.h
  lib/src/ft_math/math.c
  lib/src/system/calloc.c
Labels: Bug 🐛

#51 feat: :sparkles: Rename ft_str_append() to ft_str_extend()
  lib/include/string.h
  lib/src/string/join.c
  lib/src/string/new.c
Labels: Feature ⭐

#56 feat: :sparkles: Use linked list instead of array for scanner
  include/lexer.h
  lib/Makefile
  lib/include/libft.h
  lib/include/list.h
  lib/src/list/list.c
  makefile
  src/lexer/expansion.c
  src/lexer/lexer.c
  src/lexer/scanner_list.c
  src/lexer/scanner_util.c
  src/lexer/scanner_util2.c
Labels: Feature ⭐

#59 feat: ✨ AST Tree viewer and utils
  README.md
  include/api.h
  include/ast_node.h
  include/ast_type.h
  include/builtin.h
  include/minishell.h
  include/minishell_type.h
  include/parser.h
  include/tree.h
  lib/include/string.h
  lib/src/list/list.c
  lib/src/string/array.c
  lib/src/string/join.c
  lib/src/string/new.c
  lib/src/string/split.c
  lib/src/string/util2.c
  makefile
  src/api/exec.c
  src/api/path.c
  src/api/util.c
  src/builtin/util.c
  src/parser/del.c
  src/parser/new1.c
  src/parser/new2.c
  src/tree/repr1.c
  src/tree/repr2.c
Labels: Feature ⭐

#63 feat: :sparkles: expansion setup
  include/lexer.h
  include/parser.h
  makefile
  src/lexer/expansion.c
  src/lexer/lexer.c
  src/lexer/scanner.c
  src/lexer/scanner_list.c
  src/lexer/scanner_util.c
  src/lexer/scanner_util2.c
  src/lexer/scanner_util3.c
  src/lexer/util.c
  src/parser/del.c
  src/parser/new1.c
Labels: Feature ⭐

#65 feat: :sparkles: Add expansion scan
  include/lexer.h
  makefile
  src/lexer/expansion.c
  src/lexer/scanner.c
  src/lexer/scanner_util3.c
  src/lexer/util.c
  src/lexer/util2.c
Labels: Feature ⭐

#66 feat: :sparkles: Improve expansion scan with brace
  include/lexer.h
  src/lexer/scanner.c
  src/lexer/scanner_util.c
  src/lexer/scanner_util3.c
  src/lexer/util2.c
Labels: Feature ⭐

#44 feat: :sparkles: Improve lexer_tokenizer and Add lexer()
  include/ast_type.h
  include/lexer.h
  makefile
  src/lexer/expansion.c
  src/lexer/lexer.c
  src/lexer/lexer_tokenizer.c
  src/lexer/tokenizer.c
  src/parser/new1.c
  src/prompt/prompt.c
Labels: Feature ⭐

#68 단일 명령어 & 파이프라인 실행 기초
  .gitignore
  include/api.h
  include/ast_type.h
  lib/Makefile
  lib/include/system.h
  lib/src/system/write.c
  makefile
  src/api/argv.c
  src/api/exec.c
  src/api/file.c
  src/api/path.c
  src/api/pipe.c
  src/api/redirect.c
  src/api/signal.c
  src/api/util.c
Labels: Feature ⭐

#69 feat: :sparkles: Add parser
  include/ast_type.h
  include/parser.h
  makefile
  src/parser/del.c
  src/parser/new1.c
  src/parser/new2.c
  src/parser/parser.c
  src/parser/util.c
  src/prompt/prompt.c
  src/tree/repr2.c
Labels: Feature ⭐

#71 feat: :sparkles: Add expander() -> word expansion functions
  include/lexer.h
  include/parser.h
  include/prompt.h
  makefile
  src/lexer/tokenizer.c
  src/main.c
  src/parser/expander.c
  src/parser/new2.c
  src/parser/parser.c
  src/prompt/prompt.c
Labels: Feature ⭐

#74 `AST 토큰`으로 단일 명령어 실행 구현
  include/api.h
  include/ast_type.h
  include/builtin.h
  include/exec.h
  include/minishell.h
  include/minishell_type.h
  include/parser.h
  include/prompt.h
  include/tree.h
  lib/include/dict.h
  lib/include/ft_math.h
  lib/src/ft_math/math.c
  makefile
  src/api/argv.c
  src/api/exec.c
  src/api/file.c
  src/api/path.c
  src/api/pipe.c
  src/api/shell.c
  src/api/signal.c
  src/builtin/env.c
  src/exec/argv.c
  src/exec/exec.c
  src/exec/pipe.c
  src/exec/redirect.c
  src/exec/util.c
  src/main.c
  src/parser/del.c
  src/parser/expander.c
  src/parser/new2.c
  src/parser/parser.c
  src/parser/util1.c
  src/parser/util2.c
  src/prompt/prompt.c
  src/tree/repr2.c
  supp.txt
Labels: Bug 🐛, Feature ⭐, Refactor ⚙️

#75 Shell, Context 기능 추가 && 종료 코드 저장 및 조회
  include/api.h
  include/builtin.h
  include/exec.h
  include/minishell_type.h
  makefile
  src/api/shell.c
  src/builtin/env1.c
  src/builtin/env2.c
  src/exec/context.c
  src/exec/exec.c
  src/parser/del.c
  src/prompt/prompt.c
Labels: Feature ⭐

#76 scanner 관련 함수 NULL check 및 norm 처리
  include/ast_type.h
  include/error.h
  include/lexer.h
  include/minishell.h
  makefile
  src/error/error.c
  src/lexer/dollar_scan1.c
  src/lexer/dollar_scan2.c
  src/lexer/expansion.c
  src/lexer/lexer.c
  src/lexer/metachar_scan1.c
  src/lexer/metachar_scan2.c
  src/lexer/scanner.c
  src/lexer/scanner_util.c
  src/lexer/scanner_util2.c
  src/lexer/scanner_util3.c
  src/lexer/util2.c
  src/parser/new1.c
Labels: Refactor ⚙️

#78 feat: :sparkles: Add expansion exit status ($?)
  src/lexer/dollar_scan2.c
  src/lexer/util2.c
Labels: Feature ⭐

#80 tokenizer, parser, expander 함수 NULL check 및 norm 처리
  include/error.h
  include/lexer.h
  include/parser.h
  makefile
  src/error/error.c
  src/lexer/dollar_scan1.c
  src/lexer/dollar_scan2.c
  src/lexer/lexer.c
  src/lexer/metachar_scan1.c
  src/lexer/metachar_scan2.c
  src/lexer/scanner.c
  src/lexer/scanner_util.c
  src/lexer/tokenizer.c
  src/lexer/tokenizer_util.c
  src/lexer/util2.c
  src/parser/del.c
  src/parser/expander1.c
  src/parser/expander2.c
  src/parser/parser.c
  src/parser/util1.c
  src/parser/util2.c
  src/prompt/prompt.c
Labels: Refactor ⚙️

#81 파이프 기능 추가
  include/api.h
  include/ast_type.h
  include/builtin.h
  include/exec.h
  include/minishell.h
  include/minishell_type.h
  lib/include/system.h
  lib/src/system/gnl.c
  lib/src/system/write.c
  makefile
  src/api/file.c
  src/api/redirect.c
  src/api/shell.c
  src/api/signal.c
  src/api/util.c
  src/builtin/builtin.c
  src/builtin/cd.c
  src/builtin/echo.c
  src/builtin/export.c
  src/builtin/unset.c
  src/builtin/util.c
  src/error/error.c
  src/exec/argv.c
  src/exec/context.c
  src/exec/exec.c
  src/exec/pipe.c
  src/exec/redirect.c
  src/exec/util.c
  src/parser/new2.c
  src/prompt/prompt.c
  src/tree/repr2.c
Labels: Feature ⭐

#84 feat: :sparkles: Add exitcode for lexer & parser
  include/error.h
  include/lexer.h
  include/parser.h
  src/error/error.c
  src/lexer/dollar_scan1.c
  src/lexer/dollar_scan2.c
  src/lexer/lexer.c
  src/lexer/metachar_scan1.c
  src/lexer/scanner.c
  src/lexer/scanner_util.c
  src/parser/expander1.c
  src/parser/expander2.c
  src/prompt/prompt.c
Labels: Feature ⭐

#97 Signal및 사전 관련 문제 해결
  include/builtin.h
  include/exec.h
  include/prompt.h
  lib/src/dict/drop.c
  lib/src/dict/set.c
  makefile
  src/api/env1.c
  src/api/redirect.c
  src/builtin/builtin.c
  src/builtin/util.c
  src/exec/exec.c
  src/prompt/interrupt.c
  src/prompt/prompt.c
  src/prompt/util.c
  supp.txt
Labels: Bug 🐛

#98 gnl && 출력 결과 프롬프트에 색으로 표시
  include/api.h
  include/prompt.h
  lib/Makefile
  lib/include/color.h
  lib/include/system.h
  lib/src/ft_string/new.c
  lib/src/system/alloc.c
  lib/src/system/calloc.c
  lib/src/system/gnl.c
  lib/src/system/read.c
  makefile
  src/api/shell.c
  src/api/util.c
  src/main.c
  src/prompt/prompt.c
  src/prompt/ps.c
Labels: Feature ⭐

#99 feat: :sparkles: Add mini parser for HEREDOC
  include/parser.h
  include/scanner.h
  makefile
  src/api/redirect.c
  src/parser/expander1.c
  src/parser/heredoc_parser.c
  src/prompt/prompt.c
  src/scanner/dollar_scan1.c
  src/scanner/dollar_scan2.c
  src/scanner/scanner.c
  src/scanner/util3.c
Labels: Feature ⭐

#105 메모리 에러 해결!!!
  include/lexer.h
  include/scanner.h
  src/lexer/lexer.c
  src/lexer/tokenizer.c
  src/lexer/util.c
  src/parser/expander1.c
  src/parser/expander2.c
  src/parser/heredoc_parser.c
  src/parser/new1.c
  src/parser/new2.c
  src/parser/parser.c
  src/parser/util2.c
  src/prompt/prompt.c
  src/scanner/dollar_scan1.c
  src/scanner/dollar_scan2.c
  src/scanner/expansion.c
  src/scanner/metachar_scan1.c
  src/scanner/metachar_scan2.c
  src/scanner/scanner.c
  src/scanner/scanner_list.c
  src/scanner/util.c
Labels: Refactor ⚙️

#106 빌트인 오류 해결
  include/api.h
  include/builtin.h
  include/prompt.h
  lib/include/dict.h
  lib/include/system.h
  lib/src/dict/set.c
  lib/src/dict/status.c
  lib/src/dict/util.c
  lib/src/ft_string/array.c
  lib/src/system/gnl.c
  logo.txt
  src/api/env1.c
  src/api/env2.c
  src/api/file.c
  src/api/signal.c
  src/api/util.c
  src/builtin/cd.c
  src/builtin/echo.c
  src/builtin/env.c
  src/builtin/export.c
  src/builtin/pwd.c
  src/exec/exec.c
  src/prompt/interrupt.c
Labels: Bug 🐛, Feature ⭐, Refactor ⚙️

#109 refactor: :recycle: Refactor shell_heredoc and check norm
  include/api.h
  makefile
  src/api/heredoc.c
  src/api/redirect.c
  src/api/util.c
  src/parser/heredoc_parser.c
  src/scanner/dollar_scan2.c
  src/scanner/metachar_scan1.c
Labels: Refactor ⚙️
